apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels:
    app: {{ .Chart.Name }}
data:
  application.yaml: |
    spring:
      profiles:
        active: prod
    server:
      port: 8081
    application:
      name: demo-app
    environment: prod
