# helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        checksum/resources: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: JAVA_OPTS
          value: "-Xmx{{ .Values.javaOpts.heapSize.max }} -Xms{{ .Values.javaOpts.heapSize.min }} -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError"
        - name: SERVER_PORT
          value: "8081"
        - name: SPRING_CONFIG_MAP
          value: "{{ .Chart.Name }}-config"
        volumeMounts:
        - name: config-volume
          #mountPath: /config
          mountPath: /resources/application.yaml
          #mountPath: /resources/application.yaml
          subPath: application.yaml
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-config
          #items:
          #- key: application
          #  path: application.yaml
          #- key: environment
          #  path: environment.properties