# helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: argocd
  labels:
    app: demo-app
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    app: demo-app
