# helm/values.yaml
replicaCount: 2

image:
  repository: parkcheonghun/demo-app
  tag: 20
  pullPolicy: IfNotPresent

service:
  name: demo-app
  type: ClusterIP
  port: 8081

resources:
  limits:
    cpu: "1"
    memory: "768Mi"
  requests:
    cpu: "500m"
    memory: "384Mi"

livenessProbe:
  httpGet:
    #path: /actuator/health
    path: /hello
    port: 8081
  initialDelaySeconds: 90
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  httpGet:
    #path: /actuator/health
    path: /hello
    port: 8081
  initialDelaySeconds: 45
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 5

ingress:
  enabled: true
  #ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
        #- path: /actuator/health
        - path: /hello
          pathType: Prefix

config:
  application-name: demo-app
  environment: prod

imagePullSecrets:
  - name: regcred

javaOpts:
  heapSize:
    min: "256m"
    max: "512m"
