# helm/values.yaml
replicaCount: 2

image:
  repository: parkcheonghun/img-demo-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8081

resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "500m"
    memory: "256Mi"

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5

ingress:
  enabled: true
  ingressClassName: nginx
  host: demo.local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /

config:
  application-name: demo-app
  environment: prod